# Generated by Django 4.2.3 on 2023-10-02 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=40, verbose_name='Dia da Semana')),
                ('descricao', models.TextField(max_length=100, verbose_name='Descrição')),
                ('data_registro', models.DateField(auto_now=True, verbose_name='Data de Registro')),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Setores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('representante', models.CharField(max_length=60)),
                ('numero_sala', models.BigIntegerField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Postagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60, verbose_name='Título')),
                ('conteudo', models.TextField(max_length=200, verbose_name='Conteúdo')),
                ('data_registro', models.DateField(auto_now=True, verbose_name='Data de Registro')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.categorias')),
            ],
        ),
    ]
