# Generated by Django 4.2.3 on 2023-10-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_setores_numero_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setores',
            name='numero_sala',
            field=models.IntegerField(),
        ),
    ]
