# Generated by Django 4.2.4 on 2023-10-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_rename_data_registro_cardapios_car_data_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='cat_categoria',
            field=models.CharField(max_length=45, verbose_name='Categoria'),
        ),
    ]
