# Generated by Django 4.2.3 on 2023-10-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_categorias_cat_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagens',
            name='pos_cat_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.categorias', verbose_name='Categoria'),
        ),
    ]
