# Generated by Django 4.2.4 on 2023-10-20 12:47

from django.db import migrations, models
from django.utils.text import slugify

DEFAULT = True

def forwards(apps, _):
    Postagens = apps.get_model("cadastros", "Postagens")
    posts = Postagens.objects.all()
    for post in posts:
        post.slug = slugify(post.pos_imagem)
        post.save()


def backwards(apps, _):
    Postagens = apps.get_model("cadastros", "Postagens")
    posts = Postagens.objects.all()
    for post in posts:
        post.slug = DEFAULT
        post.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_remove_postagens_pos_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagens',
            name='pos_imagem',
            field=models.ImageField(default=DEFAULT, upload_to='imagens/', verbose_name='Imagem'),
            preserve_default=False,
        ),

        migrations.RunPython(forwards, backwards)
    ]
