# Generated by Django 4.2.4 on 2023-10-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_alter_postagens_pos_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapios',
            name='car_dia_semana',
            field=models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira')], default='SEG', max_length=3, verbose_name='Dia da Semana'),
        ),
    ]
